spring:
  cloud:
    consul:
      config:
        enabled: true
      discovery:
#        tells the system to use IP rather than host name for discovery. !! si TRUE -> KO
        prefer-ip-address: false
#      host: 127.0.0.1
#      port: 8500