spring:
  cloud:
    consul:
      config:
#        si la config est synchronisée par consul (requiert dépdce)
        enabled: false
      discovery:
#        tells the system to use IP rather than host name for discovery. !! si TRUE -> KO
        prefer-ip-address: false
        instanceId: ${spring.application.name}:${random.value}
      host: 127.0.0.1
#      port: 8500